### ISSUE TITLE
Lossy events on ledger crashes

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1727]
## Problem

When a new batch of events $B$ are confirmed by the Ethereum oracle for some Ethereum block $h_E$, they are written to a channel in memory, and the next block to be processed by the oracle is bumped to $h_E+1$. Concurrently, at some arbitrary Namada height $h_N$, the channel is read from by the `Shell`, and the events contained within are proposed in the form of a new Ethereum events protocol transaction.

Before $B$ is proposed and propagated via CometBFT's P2P layer,  the ledger may crash. It may be possible for Ethereum events to be lost when this happens. Granted this is only a liveness concern for the Ethereum bridge if $\ge \frac{1}{3}$ of validators by stake crash and restart, it is still within the realm of possibilities.

## Solution

A simple ad-hoc fix is to reset the last processed Ethereum height in the ledger, since this value is not stored in Merkelized storage. Otherwise, we may need to perform a two-step commitment (e.g. PROPOSE-COMMIT) to the last processed Ethereum block height in the ledger, between the oracle and the shell's tasks.

**Comment by batconjurer** [comment]
I don't understand how this actually could happen. The last ethereum block height is only increased when commit block is called. Otherwise, it is "reset" just as in the proposed solution. If we have a $\ge \frac{1}{3}$ crash around commiting a block, we actually have a massive chain fork, so there are much larger problems than the events being lost.
