### ISSUE TITLE
Namada node status before genesis time

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#2495]
Namada should inform the user about the status of the node before genesis time.

**Comment by shurinov** [comment]
It's a necessary thing. to make sure it's set up correctly

**Comment by reversesigh** [comment]
The node status does post.

```  2024-01-31T18:31:51.977788Z  INFO namada_apps::node::ledger: Waiting for ledger genesis time: DateTimeUtc(2024-02-01T18:00:00Z), time left: 84488.022213607s
```  
What validators especially appreciate is validator status - so if Namada could still generate a cometbft folder pre-genesis, so that the pubkey can be tested against genesis to prove validator status then validators can be sure they have the correct key. 

Having the priv_validator_key would also allow testing of remote signing like Horcrux pre-genesis, rather than testing when the chain is already live.

**Comment by tecnodes-network** [comment]
follow up.

would be nice to see if it detected that node is a validator node.

**Comment by tungdh1** [comment]
" This node is a validator" The announcement is small but very necessary, follow it

**Comment by encipher88** [comment]
Agree this logs would be helpful

**Comment by kw1knode** [comment]
+1

**Comment by CroutonDigital** [comment]
In previous versions we could see if pre-genesis file is correct , we had 2 confirmations in logs, that this node is validator node, in this version we have no information

**Comment by Web3Slimchance** [comment]
+1
