### ISSUE TITLE
Add a metrics endpoint

### ISSUE THREAD

**Issue by SimSaladin** [anoma/namada#27]
A Prometheus-compatible metrics endpoint (`/metrics` on some configurable port) would be great for monitoring nodes. A Prometheus instance somewhere does all the heavy lifting of scraping the data and storing it as time series. The metrics endpoint just needs to respond with the current values of interesting application-specific data points.

Tendermint also has a metrics endpoint that can be enabled in its config. Currently it's a bit awkward to enable though, because you first need to generate the tendermint config by launching anoma once, edit the tendermint config and then restart anoma.

So maybe there should be just one place in anoma configuration to configure metrics, and it affects tendermint too. We could even aggregate the metrics from tendermint in order to avoid having two metrics endpoints (i.e. two ports for metrics) per node.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763045226887) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
@Fraccaman is there anything left for this (other than updates with ABCI++)?

**Comment by Fraccaman** [comment]
We are currently just using the tendermint prometheus endpoint, we could integrate some more specific anoma/namada metrics.

**Comment by diceride** [comment]
The modern approach would be to add OpenTelemetry to the p2p layer and allow the user to configure a custom [collector](https://opentelemetry.io/docs/collector/) endpoint to receive, process and export telemetry data. Instead of being locked-in by a single vendor, OpenTelemetry provides an open standard for generating, collecting, and exporting application telemetry across any number of backend systems, including Prometheus.

You can find an overview of configurable exporters in the [opentelemetry-collector-contrib/exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter) directory.

For Namada, OpenTelemetry can be configured with the [tracing](https://github.com/tokio-rs/tracing) framework. OpenTelemetry only needs to be configured once, for example when initializing a new Namada node.

https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/

Example

![example](https://user-images.githubusercontent.com/72995223/197396388-1ea2669c-85ec-491e-a469-f7bd6d9fc591.png)

**Comment by diceride** [comment]
The modern approach would be to add OpenTelemetry to the p2p layer and allow the user to configure a custom [collector](https://opentelemetry.io/docs/collector/) endpoint to receive, process and export telemetry data. Instead of being locked-in by a single vendor, OpenTelemetry provides an open standard for generating, collecting, and exporting application telemetry across any number of backend systems, including Prometheus.

You can find an overview of configurable exporters in the [opentelemetry-collector-contrib/exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter) directory.

For Namada, OpenTelemetry can be configured with the [tracing](https://github.com/tokio-rs/tracing) framework. OpenTelemetry only needs to be configured once, for example when initializing a new Namada node.

https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/

Example

![example](https://user-images.githubusercontent.com/72995223/197404822-74ab5173-d543-4da8-ad3e-8e5b65252a41.png)

**Comment by cwgoes** [comment]
@Fraccaman what is the status of this / do you think there is important work remaining to be done before Namada mainnet?

**Comment by Fraccaman** [comment]
I think we can leave this for sometime in the future, we already have the tendermint prometheus endpoint.
