### ISSUE TITLE
Lost ibc tokens when send to shield address 

### ISSUE THREAD

**Issue by encipher88** [anoma/namada#2758]
I checked how namadac ibc-gen-shielded works for example

 when sending from cosmos type chains to namada, if we send tokens to the zknam address, then using the pre-generated memo code in ibc-gen-shielded, the tokens arrive without problems.

  But if we send through Hermes or through any cli of the same cosmos or osmo or stargaze without specifying the memo, then the funds do not arrive.
 
  The question is where do they come, where do they get lost, are they burned?

 It seems to me that this is a serious  problem for the security of sending tokens, because even if we send tokens to the exchange without memo, where it is often used, the operator can manually distribute these funds, but not in namada.

  So my proposal is to make logic that protects the sending of ibc tokens to a shield address

 In namada - this is easy to do by simply adding either automatic generation of ibc-gen-shielded in the ibc-transfer sending logic, automatic substitution of the memo-path value

 Well, unfortunately, we cannot add it to other clients cosmos type.
  The maximum we can do is PR in Hermes which will analyze the sending address if it starts with zknam and then prohibit sending tokens without specifying the memo,
 
 but this is only a half-way solution, which means that on the namada side we also have to come up with some kind of buffer that will allow us to pull out the stuck tokens from the address by specifying the same value from the memo, but manually.

**Comment by zenodeapp** [comment]
I reckon shielded IBC transfers always first land in the MASP contract? What if this contains logic to return the funds back to the sender via ibc again if it's invalid instead of the now loss of funds?

Though, this would require having the necessary funds to do this revert transaction. And could probably easily be exploited and drained if abused (economically a bad move for the bad actor though, but something to still consider).

Takes me to the point of introducing a special type of ibc transfer (just a specific type of memo) that allows the user who lost their funds to reclaim it by sending this special refund tx with the appropriate amount of fees (for the refund). What this would do is trigger the MASP to return all the "failed" vaulted funds this sender send back over ibc.

**Comment by encipher88** [comment]
Yes, this is exactly what I’m talking about, maybe just other words. But this definitely needs to be done.  
Btw
It would also be a good idea to check on the keplr side because most will use it.  If you remember in Keplr in nemo, it was previously possible to send both a mnemonic and a seed phrase by accident, but this has been fixed.

**Comment by yito88** [comment]
By #2631, shielded IBC transfers will not use ICS-20 memo field anymore

**Comment by brentstone** [comment]
Seems like this will be addressed in the next release, so closing.
