### ISSUE TITLE
Problem with voting

### ISSUE THREAD

**Issue by katekrasv** [anoma/namada#2865]
Faced with the problem of not being able to vote on behalf of the validator. 
Validator asset from the second era, in the jail was not. 
Example on the vote 266. At the moment voting is available for validators. 

When trying to vote we get an error:
```
namadac vote-proposal --proposal-id 266 --vote yay --address tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3
Looking-up public key of tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3 from the ledger...
Error: 
   0: Voter address must have delegations

Location:
   /root/namada/crates/apps/src/lib/cli/client.rs:188
```

The validator address is correct:
```
namadac find-validator --tm-address $(curl -s http://127.0.0.1:26657/status | jq -r '.result.validator_info.address') | grep "Found validator address" | awk -F '"' {'print $2'}
tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3
```

Stake is active:

```
namada client bonded-stake | grep tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3
  tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3: 28961.000000
```

**Comment by Fraccaman** [comment]
try to use `--force`

**Comment by katekrasv** [comment]
> try to use `--force`, this is just a client side bug.

This doesn't help, the problem is still the same

```
namadac vote-proposal --proposal-id 266 --vote yay --address tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3 --force
Looking-up public key of tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3 from the ledger...
Error: 
   0: Voter address must have delegations

Location:
   /root/namada/crates/apps/src/lib/cli/client.rs:188

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by Fraccaman** [comment]
ah probably because we are not having the correct condition here :( i think you need to self bond 1 nam and then it should work. Ill prepare a patch.

**Comment by katekrasv** [comment]
> ah probably because we are not having the correct condition here :( i think you need to self bond 1 nam and then it should work. Ill prepare a patch.

After creating the validator, I made a self bond on the validator.
I'll try to repeat it.
Since the problem needs a software fix, is this considered a bug?

**Comment by opsecx** [comment]
> > ah probably because we are not having the correct condition here :( i think you need to self bond 1 nam and then it should work. Ill prepare a patch.
> 
> 
> 
> After creating the validator, I made a self bond on the validator.
> 
> I'll try to repeat it.
> 
> Since the problem needs a software fix, is this considered a bug?

did you self-bond on the validator *from* the validator?

**Comment by brentstone** [comment]
@katekrasv As @opsecx is suggesting, I think you probably did not actually self-bond. Rather, you bonded from an implicit account address that you also own to your validator address, i.e. from one account to a different account. On-chain, the protocol does not associate the implicit address with your validator address (which is an Established address) and so does not treat this is a self-bond, which would imply that you bonded from your validator address to itself.

As @fraccaman mentioned, self-bonding with something like `namadac bond --validator $VALIDATOR_ADDRESS` would sort your issue. However, this is clearly a client-side bug that we will patch up anyway, since you should be able to vote even without a self-bond, as you do have delegators.
