### ISSUE TITLE
Account for negative inflation in PD controller

### ISSUE THREAD

**Issue by sug0** [anoma/namada#3231]
From the refactor in #2575:
https://github.com/anoma/namada/blob/4ed62290d3d3062b655c9bfc7cf08bd1b2230fd8/crates/controller/src/lib.rs#L78-L81

**Comment by brentstone** [comment]
What do you mean by account for negative inflation in PD controller here? `Dec` can also contain negative values. I put the TODO here in case we wanted to do arithemtic just using integers rather than the `Dec` type, though I think perhaps we can remove the TODO. These numbers need to be signed since `control` may be negative.

**Comment by sug0** [comment]
removed in #3234
