### ISSUE TITLE
Shielding does not automatically reveal a pk

### ISSUE THREAD

**Issue by sug0** [anoma/namada#3552]
When you attempt to shield with an account whose pk hasn't been revealed yet, the multitoken VP and masp VP both fail with a "signature threshold not met" error.

The returned client message isn't too helpful in figuring out the cause of this error. We should either:

1. Automatically send a reveal pk transaction along with the shielding transaction, or...
2. State the reason of the failure (in this case, the public key hasn't been revealed yet, thus it's missing in storage).

## Example flow

https://pastebin.com/GSRdwyTm

**Comment by brentstone** [comment]
Included the auto reveal-pk for `shield` in #3594.

But another question arises: should we be revealing the pk for all source addresses that do not have their pk revealed yet, since transfers now support multiple sources? This would apply for `shield` and `transparent-transfer` as well. Right now we only consider the first source I believe.

@grarco @sug0

**Comment by sug0** [comment]
Since we went with option 1), I guess that should be the default behavior for all source addrs.

**Comment by grarco** [comment]
An additional note, I believe since we have tx batches now we could pack all the reveal-pk transactions and the desired tx together and submit a single batch, I've mentioned this thing here https://github.com/anoma/namada/issues/1879#issuecomment-2278371087

**Comment by Fraccaman** [comment]
yeah agree, this is what the interface team is doing
