### ISSUE TITLE
The problem with token allocating.

### ISSUE THREAD

**Issue by yopo99922** [anoma/namada#3814]
Good day. 
I am contacting you with the following problem. I am a donor of the Namada project on git coin. I remember that once I filled out a form to receive 600-700 coins (I remember it for sure!) But in the last list for receiving allocations I do not see my wallet. Please check the information and help me solve this problem. 
Thanks in advance.
my tnam is tnam1qrh9ulr352wv5kekg8c7gxzlcspz4peeh54ldp4j

**Comment by Darrenpeaker** [comment]
> I am contacting you with the following problem. I am a donor of the Namada project on git coin. I remember that once I filled out a form to receive 600-700 coins (I remember it for sure!) But in the last list for receiving allocations I do not see my wallet. Please check the information and help me solve this problem.
> Thanks in advance.
> my tnam is tnam1qrh9ulr352wv5kekg8c7gxzlcspz4peeh54ldp4j


@yopo99922  It seems that you're facing an issue with receiving your allocation for the Namada project on Gitcoin. Since you remember filling out a form to receive coins but don't see your wallet in the latest list, it sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID GIT07638
Please see the link below to our dedicated support line:
[Gitcoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by brentstone** [comment]
The comment just deleted from this issue is not from a trusted member of the larger Namada community. If you desire support for this issue, please contact Gavin at `gavinly` on Discord
