### ISSUE TITLE
Voting as a (pre-genesis?) delegator fails

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada#4029]
I tried voting with my validator and two delegators keys. One of these delegator keys has only pre-genesis bonds, while the other also has post genesis bonds.

Voting with the delegator key that only has pre-genesis bonds fails with: "Invalid transaction section signature: RuntimeError: The section signature is invalid: signature threshold not met: (0 < 1)".

The rest does succeed.

I have to add that the delegator key with post genesis bonds also failed before I added extra bonds so that's why I suspect this to be the issue.

Command used: `namadac vote-proposal --vote yay --address alias --proposal-id 2`

**Comment by zenodeapp** [comment]
I just now added a bond to this delegator key that only had pre bonds and I can vote with it now. No more signature not met error. So seems like the theory checks out, but I wouldn't know for sure what is exactly up.

**Comment by brentstone** [comment]
Your first attempt at voting failed with the invalid signature threshold because you hadn't yet revealed your public key to the ledger (so it could not find one associated with your address). Running `namadac reveal-pk` and then reattempting would have fixed it.

This succeeded after a bond because a bond TX submits a reveal-pk TX if it is needed.
