### ISSUE TITLE
MASP primitives in vp_prelude

### ISSUE THREAD

**Issue by juped** [anoma/namada#54]
The MASP primitives from anoma/masp should be made available for VPs to use.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762709660417) by [Unito](https://www.unito.io)

**Comment by murisi** [comment]
@cwgoes @juped I believe this is done: we found a way to get the VP WASM code to depend on the `anoma/masp` crate without breaking the WASM build. This issue is also slightly less relevant because some of the MASP validation code have been put into the VP host environment, that is, outside the actual WASM code.
