### ISSUE TITLE
MASP validity predicate

### ISSUE THREAD

**Issue by juped** [anoma/namada#56]
Depends on anoma/namada#54, anoma/namada#55.

Desired abilities:

* stores notes/nullifiers
* verifies (proof, notes nullifiers) sets from transactions
* exposes readable Merkle tree roots for clients in its storage
* holds assets (just balances for now?)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762709310621) by [Unito](https://www.unito.io)

**Comment by murisi** [comment]
@cwgoes If I'm not mistaken, I believe @juped has completed these tasks. But I would need to review the validity predicate code to ascertain whether the validation is sufficient, i.e. to ensure that the VP does not in any circumstances accept any transactions that should be rejected.

**Comment by murisi** [comment]
@juped Ah, I see. Great! Regardless of whether or not we port, I see a potential issue at https://github.com/anoma/namada/blob/main/wasm/wasm_source/src/vp_masp.rs#L75 . If the client somehow manages to construct a `Transaction` with `shielded_tx.value_balance` equal to zero (and hence having no components), the VP might crash in the process of `unwrap`ping.

More generally to prevent potential exploits, we should probably try (whether here or in the port) to enforce the 4 conditions at https://github.com/anoma/namada/blob/main/documentation/specs/src/masp/ledger-integration.md#boundary-conditions . They serve to ensure that the outer `Transfer` object is consistent with the inner `Transaction` in terms of the numbers and fields of the transparent inputs/outputs. I think we haven't really had an issue here yet because the CLI client has been well behaved so far.

**Comment by murisi** [comment]
> yes; but we were discussing porting it to native, which would be so much less flaky
I'm not sure what the status of this is, but I've identified some potential further issues in the MASP VP code as it currently stands: https://github.com/anoma/namada/issues/1373 .
